SocialAppSBurris/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("socialapp.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialapp/urls.py
from django.urls import path
from . import views

app_name = 'socialapp'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:socialpost_id>/vote/", views.vote, name="vote"),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
]

socialapp/models.py
import datetime
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class Socialpost(models.Model):
    post_title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='socialposts/images/', blank=True, null=True)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.post_title

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    socialpost = models.ForeignKey(Socialpost, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

socialapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField()


class SignInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

socialapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from .models import Choice, Socialpost
from django.contrib.auth import login, authenticate, logout
from .forms import SignUpForm, SignInForm


class IndexView(generic.ListView):
    template_name = "socialapp/index.html"
    context_object_name = "latest_socialpost_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Socialpost.objects.order_by("-pub_date")[:200]

    @method_decorator(login_required(login_url='socialapp:signin'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class DetailView(generic.DetailView):
    model = Socialpost
    template_name = "socialapp/detail.html"

    @method_decorator(login_required(login_url='socialapp:signin'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ResultsView(generic.DetailView):
    model = Socialpost
    template_name = "socialapp/results.html"

    @method_decorator(login_required(login_url='socialapp:signin'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def vote(request, socialpost_id):
    socialpost = get_object_or_404(Socialpost, pk=socialpost_id)
    try:
        selected_choice = socialpost.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "socialapp/detail.html",
            {
                "socialpost": socialpost,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("socialapp:results", args=(socialpost.id,)))


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('socialapp:index')
    else:
        form = SignUpForm()
    return render(request, 'socialapp/signup.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('socialapp:index')
            else:
                messages.error(request, 'Wrong username or password entered.')
    else:
        form = SignInForm()

    return render(request, 'socialapp/signin.html', {'form': form})


def signout(request):
    logout(request)
    return redirect('socialapp:index')

socialapp/templates/socialapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- for different devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'socialapp/style.css' %}">
</head>
<body>
<h1>Social App Post Details</h1>
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}!</p>
{% endif %}
<form action="{% url 'socialapp:vote' socialpost.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ socialpost.post_title }}</h1></legend>
    {% if socialpost.image %}
        <img src="{{ socialpost.image.url }}" alt="{{ socialpost.post_title }}">
    {% endif %}
    <h4>Description:</h4>
    <p>{{ socialpost.description }}</p>
    <h4>Published On:</h4>
    <p>{{ socialpost.pub_date }}</p>
    <h4>Click To Vote:</h4>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in socialpost.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</fieldset>
</form>
<nav>
    <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'socialapp:results' socialpost.id%}'">See Votes</button>
    <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'socialapp:index' %}'">Home</button>

    {% if user.is_authenticated %}
        {# Show the logout button if the user is authenticated #}
        {% include 'socialapp/signout.html' %}
    {% else %}
        {# Show the login and signup links if the user is not authenticated #}
        <a href="{% url 'socialapp:signin' %}">Sign In</a> | <a href="{% url 'socialapp:signup' %}">Sign Up</a>
    {% endif %}

</nav>
</body>
</html>

socialapp/templates/socialapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- for different devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social App Home</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'socialapp/style.css' %}">

</head>
<body>
    <h1>Social App Home</h1>
    {% if user.is_authenticated %}
    <nav>
        {# Show the user name if the user is authenticated #}
        <p>Welcome, {{ user.username }}!</p>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Help
        </button>
        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">App Instructions</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <p> To see the post details and vote click on the post title</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        {# Show the logout button if the user is authenticated #}
        {% include 'socialapp/signout.html' %}
        {% else %}
        {# Show the login and signup links if the user is not authenticated #}
        <a href="{% url 'socialapp:signin' %}">Sign In</a> | <a href="{% url 'socialapp:signup' %}">Sign Up</a>
        {% endif %}
    </nav>
    <h2>All Posts</h2>
        {% if latest_socialpost_list %}
            <ul>
            {% for socialpost in latest_socialpost_list %}
                <li>
                    <form>
                        <fieldset>
                        <legend><h2><a href="{% url 'socialapp:detail' socialpost.id %}">{{ socialpost.post_title }}</a></h2></legend>
                        {% if socialpost.image %}
                            <img src="{{ socialpost.image.url }}" alt="{{ socialpost.post_title }}">
                        {% endif %}
                        <h4>Description:</h4>
                        <p>{{ socialpost.description }}</p>
                        </fieldset>
                    </form>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No posts are available.</p>
        {% endif %}
</body>
</html>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

socialapp/templates/socialapp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- for different devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'socialapp/style.css' %}">
</head>
<body>
<h1>Social App Post Votes</h1>
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}!</p>
{% endif %}
<form>
    <fieldset>
        <legend><h1>{{ socialpost.post_title }}</h1></legend>
        {% if socialpost.image %}
            <img src="{{ socialpost.image.url }}" alt="{{ socialpost.post_title }}">
        {% endif %}
        <h4>Description:</h4>
        <p>{{ socialpost.description }}</p>
        <h4>Votes:</h4>
        <ul>
        {% for choice in socialpost.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        </ul>
    </fieldset>
</form>
<nav>
    <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'socialapp:detail' socialpost.id%}'">Vote Again</button>
    <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'socialapp:index' %}'">Home</button>
    {% if user.is_authenticated %}
        {# Show the logout button if the user is authenticated #}
        {% include 'socialapp/signout.html' %}
    {% else %}
        {# Show the login and signup links if the user is not authenticated #}
        <a href="{% url 'socialapp:signin' %}">Sign In</a> | <a href="{% url 'socialapp:signup' %}">Sign Up</a>
    {% endif %}
</nav>
</body>
</html>

socialapp/templates/socialapp/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- for different devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'socialapp/style.css' %}">
</head>
<body>
<div>
    <h1>Sign In</h1>
    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign In</button>
        <p>Click Sign Up to Create an Account</p>
        <div>
            <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'socialapp:signup' %}'">Sign Up</button>
        </div>
    </form>
</div>
<div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>

    {% endif %}
</div>
<script>
    // Automatically close error messages after 5 seconds (adjust as needed)
    setTimeout(function() {
        document.querySelector('.messages').style.display = 'none';
    }, 3000);
</script>
</body>
</html>

socialapp/templates/socialapp/signout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Out</title>
</head>
<body>
<form method="post" action="{% url 'socialapp:signin' %}">
    {% csrf_token %}
    <button type="submit">Sign Out</button>
</form>
</body>
</html>

socialapp/templates/socialapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- for different devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign UP</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'socialapp/style.css' %}">
</head>
<body>
    <div>
        <h1>Sign Up</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign Up</button>

            <p>Click Sign In if You Have Already Created an Account</p>
            <div>
                <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'socialapp:signin' %}'">Sign In</button>
            </div>
        </form>
    </div>
</body>
</html>